### ISSUE TITLE
YFS (task 3)

### ISSUE THREAD

**Issue by eugenevlasov** [kotborealis/os_lab#3]
1) yfs -c
2) yfs -a logger.h
3) yfs -a yfs
4) yfs -d logger.h
5) yfs -r yfs

каша на экране, которая еще и разноцветная

**Comment by kotborealis** [comment]
Третий пункт не могу воспроизвести в таком же виде, но если сделать `cp yfs yfs_copy && yfs -a yfs_copy` и потом остальные пункты, то всё работает как и должно, вывод `yfs -r yfs_copy` и `cat yfs_copy` совпадает.

[Запись терминала](https://asciinema.org/a/mh6E16JN5TZuAslixJvbPty29)

**Comment by eugenevlasov** [comment]
Да, все работает. Сделал вывод этой каши в файлик - он нормально запустился
