### ISSUE TITLE
процесс, пишущий в shmem, выводит на экран time()

### ISSUE THREAD

**Issue by eugenevlasov** [kotborealis/os_lab#4]
ftok key 4017095237
No shared memory, trying to create new one
~~Host~~
|--> time()
|--> time()
|--> time()
|--> time()
|--> time()

**Comment by kotborealis** [comment]
Все как ожидается. По условию лабы он не обязан выводить что-то на экран 🐴.

То, что пишет первый процесс в шмем, выводит второй процесс.

Но соль понял, исправлю, чтобы первый процесс тоже выводил то, что он пишет.
